### ISSUE TITLE
Simulator launching failure

### ISSUE THREAD

**Issue by priand** [robovm/robovm-eclipse#19]
The simulator fails to correctly display an app when it relaunched after been modified.
Here is how to reproduce:
- Add the UICatalog demo to the workspace
- Launch the app in debug from the context menu
it displays the main view, so it works. Don't shutdown the simulator
- Modify one file in the project (ex: add a dummy member to MyTableView)
- Launch again with the same debug option and the simulator will then show a black screen

Workarounds:
- Go to the home screen in the simulator and click back on the app icon
- Terminate the app in the eclipse debug window
- Reset the simulator settings

**Comment by badlogic** [comment]
This should be fixed for a long time now :)
