### ISSUE TITLE
New iOS project wizard window is too small

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-eclipse#43]
Doesn't fit on a 1280x800 screen:

![screen shot 2015-03-09 at 19 39 23](https://cloud.githubusercontent.com/assets/135765/6561827/841cff8c-c694-11e4-88eb-b883afa68eef.png)

**Comment by BlueRiverInteractive** [comment]
We should probably use a [ScrolledComposite](http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fcustom%2FScrolledComposite.html) for the wizard page.

**Comment by ntherning** [comment]
Yes, I agree. Looking into it right now.

**Comment by ntherning** [comment]
Nailed it!

![screen shot 2015-03-09 at 20 27 07](https://cloud.githubusercontent.com/assets/135765/6562594/cbd484d4-c69a-11e4-8b31-33784b07a4cf.png)

**Comment by BlueRiverInteractive** [comment]
Looks cool!
