### ISSUE TITLE
M2Eclipse connector

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-eclipse#49]
The connector should look for a reference to the robovm maven plugin in the pom (and parents too?). If found it should add the `org.robovm.eclipse.RoboVMNature` and the `org.robovm.eclipse.RoboVMClassBuilder` to the Eclipse project and set up a classpath with the `org.robovm.eclipse.ROBOVM_CONTAINER` and (if it's an iOS project) the `org.robovm.eclipse.ROBOVM_COCOA_TOUCH_CONTAINER`.

**Comment by badlogic** [comment]
We are not going down the connector route.
