### ISSUE TITLE
[IB] IBIntegrator integration in Eclipse

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-eclipse#53]
Every project should have it's own IBIntegrator. The .ib folder will be generated in the project root. All resource folders specified in the robovm.xml should be watched by IBIntegrator, as well as all folders with compiled Java class files.

**Comment by ntherning** [comment]
Forgot we had this issue. :-) I have pushed this now. We create an `IBIntegrator` for each open RoboVM iOS project and shut it down when a project is closed.
