### ISSUE TITLE
Ensure the plugin works on Win/Linux with a warning that iOS compilation only works on Mac OS X

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-eclipse#84]

**Comment by ntherning** [comment]
Also applies to Interface Builder integration, robovm/robovm#1008. Not sure whether the proper fix for that issue is in the Eclipse/IDEA plugins or in the IB code itself.

**Comment by badlogic** [comment]
Works on Windows and Linux now. Could not reproduce the interface builder issue anymore either.
