### ISSUE TITLE
Build failed with xcode7 and robovm 1.9

### ISSUE THREAD

**Issue by liaogang** [robovm/robovm-eclipse#88]
![2015-10-23 9 32 07](https://cloud.githubusercontent.com/assets/3311527/10682533/34e02a92-7969-11e5-85d2-848c909f45fa.png)

**Comment by ntherning** [comment]
You must have some plugin or something (`Xprop`?) installed in Xcode which messes with `xcrun`. Try to run `xcrun -f clang++` on the command line and make sure you only see something like this:

```
Niklas-MacBookPro:robovm niklas$ xcrun -f clang++
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
```
